---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alone-christmas-app
  labels:
    app: alone-christmas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alone-christmas
  template:
    metadata:
      labels:
        app: alone-christmas
    spec:
      containers:
        - name: web
          image: registry.uniproject.jp/ayane/alone-christmas:0.1.3
          ports:
            - containerPort: 3000
